
CREATE TABLE IF NOT EXISTS t_document_party_config (
    id              BIGINT          NOT NULL AUTO_INCREMENT COMMENT '主键',
    site_code       VARCHAR(20)     NOT NULL                COMMENT '站点代码（US/CA/UK/EU），唯一',
    buyer_name      VARCHAR(100)    NOT NULL                COMMENT '买方中文名',
    buyer_address   VARCHAR(255)    DEFAULT NULL            COMMENT '买方地址',
    buyer_phone     VARCHAR(50)     DEFAULT NULL            COMMENT '买方电话',
    buyer_name_en   VARCHAR(100)    DEFAULT NULL            COMMENT '买方英文名',
    seller_name     VARCHAR(100)    NOT NULL                COMMENT '卖方名称',
    seller_address  VARCHAR(255)    DEFAULT NULL            COMMENT '卖方地址',
    seller_phone    VARCHAR(50)     DEFAULT NULL            COMMENT '卖方电话',
    supplier_name   VARCHAR(100)    NOT NULL                COMMENT '供应商名称',
    customer_name_tc VARCHAR(100)   NOT NULL                COMMENT '客户繁体名',
    bank_account_name   VARCHAR(100) DEFAULT NULL           COMMENT '银行账户名',
    bank_account_number VARCHAR(50)  DEFAULT NULL           COMMENT '银行账号',
    bank_name       VARCHAR(100)    DEFAULT NULL            COMMENT '银行名称',
    bank_address    VARCHAR(255)    DEFAULT NULL            COMMENT '银行地址',
    swift_code      VARCHAR(20)     DEFAULT NULL            COMMENT 'SWIFT代码',
    create_time     DATETIME        DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time     DATETIME        DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    deleted         TINYINT(1)      DEFAULT 0               COMMENT '逻辑删除（0=未删除，1=已删除）',
    PRIMARY KEY (id),
    UNIQUE KEY uk_site_code (site_code, deleted)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='FBA单据交易方配置';




INSERT INTO `musheng_tax`.`t_document_party_config` (`id`, `site_code`, `buyer_name`, `buyer_address`, `buyer_phone`, `buyer_name_en`, `seller_name`, `seller_address`, `seller_phone`, `supplier_name`, `customer_name_tc`, `bank_account_name`, `bank_account_number`, `bank_name`, `bank_address`, `swift_code`, `create_time`, `update_time`, `deleted`) VALUES (1, 'US', '东莞市慕声商贸有限公司', '广东省东莞市虎门镇连升路82号虎门万达广场2栋606房', '18575382420', 'Dongguan Musheng Trade Co., Ltd.', 'Hong Kong Andeo Group Limited', 'ROOM 1201, 12/F TAI SANG BANK BUILDING 130-132 DES VOEUX ROAD, CENTRAL HONGKONG', '00852-54682464', 'Hong Kong Andeo Group Limited', '東莞市慕聲商貿有限公司', 'Hong Kong Andeo Group Limited', '012-878-0-001234-5', 'Bank of China (Hong Kong) Limited', 'Bank of China Tower, 1 Garden Road, Central, Hong Kong', 'BKCHHKHH', '2026-03-22 12:59:43', '2026-03-22 13:31:56', 0);
INSERT INTO `musheng_tax`.`t_document_party_config` (`id`, `site_code`, `buyer_name`, `buyer_address`, `buyer_phone`, `buyer_name_en`, `seller_name`, `seller_address`, `seller_phone`, `supplier_name`, `customer_name_tc`, `bank_account_name`, `bank_account_number`, `bank_name`, `bank_address`, `swift_code`, `create_time`, `update_time`, `deleted`) VALUES (2, 'CA', '东莞市慕声商贸有限公司', '广东省东莞市虎门镇连升路82号虎门万达广场2栋606房', '18575382420', 'Dongguan Musheng Trade Co., Ltd.', 'Hong Kong Andeo Group Limited', 'ROOM 1201, 12/F TAI SANG BANK BUILDING 130-132 DES VOEUX ROAD, CENTRAL HONGKONG', '00852-54682464', 'Hong Kong Andeo Group Limited', '東莞市慕聲商貿有限公司', 'Hong Kong Andeo Group Limited', '012-878-0-001234-5', 'Bank of China (Hong Kong) Limited', 'Bank of China Tower, 1 Garden Road, Central, Hong Kong', 'BKCHHKHH', '2026-03-22 12:59:43', '2026-03-22 13:31:56', 0);
INSERT INTO `musheng_tax`.`t_document_party_config` (`id`, `site_code`, `buyer_name`, `buyer_address`, `buyer_phone`, `buyer_name_en`, `seller_name`, `seller_address`, `seller_phone`, `supplier_name`, `customer_name_tc`, `bank_account_name`, `bank_account_number`, `bank_name`, `bank_address`, `swift_code`, `create_time`, `update_time`, `deleted`) VALUES (3, 'UK', '东莞市慕声商贸有限公司', '广东省东莞市虎门镇连升路82号虎门万达广场2栋606房', '18575382420', 'Dongguan Musheng Trade Co., Ltd.', 'Hong Kong Andeo Group Limited', 'ROOM 1201, 12/F TAI SANG BANK BUILDING 130-132 DES VOEUX ROAD, CENTRAL HONGKONG', '00852-54682464', 'Hong Kong Andeo Group Limited', '東莞市慕聲商貿有限公司', 'Hong Kong Andeo Group Limited', '012-878-0-001234-5', 'Bank of China (Hong Kong) Limited', 'Bank of China Tower, 1 Garden Road, Central, Hong Kong', 'BKCHHKHH', '2026-03-22 11:45:09', '2026-03-22 12:54:54', 0);
INSERT INTO `musheng_tax`.`t_document_party_config` (`id`, `site_code`, `buyer_name`, `buyer_address`, `buyer_phone`, `buyer_name_en`, `seller_name`, `seller_address`, `seller_phone`, `supplier_name`, `customer_name_tc`, `bank_account_name`, `bank_account_number`, `bank_name`, `bank_address`, `swift_code`, `create_time`, `update_time`, `deleted`) VALUES (4, 'EU', '东莞市慕声商贸有限公司', '广东省东莞市虎门镇连升路82号虎门万达广场2栋606房', '18575382420', 'Dongguan Musheng Trade Co., Ltd.', 'Hong Kong Andeo Group Limited', 'ROOM 1201, 12/F TAI SANG BANK BUILDING 130-132 DES VOEUX ROAD, CENTRAL HONGKONG', '00852-54682464', 'Hong Kong Andeo Group Limited', '東莞市慕聲商貿有限公司', 'Hong Kong Andeo Group Limited', '012-878-0-001234-5', 'Bank of China (Hong Kong) Limited', 'Bank of China Tower, 1 Garden Road, Central, Hong Kong', 'BKCHHKHH', '2026-03-22 12:59:43', '2026-03-22 13:31:56', 0);
INSERT INTO `musheng_tax`.`t_document_party_config` (`id`, `site_code`, `buyer_name`, `buyer_address`, `buyer_phone`, `buyer_name_en`, `seller_name`, `seller_address`, `seller_phone`, `supplier_name`, `customer_name_tc`, `bank_account_name`, `bank_account_number`, `bank_name`, `bank_address`, `swift_code`, `create_time`, `update_time`, `deleted`) VALUES (5, 'JP', '东莞市慕声商贸有限公司', '广东省东莞市虎门镇连升路82号虎门万达广场2栋606房', '18575382420', 'Dongguan Musheng Trade Co., Ltd.', 'Hong Kong Andeo Group Limited', 'ROOM 1201, 12/F TAI SANG BANK BUILDING 130-132 DES VOEUX ROAD, CENTRAL HONGKONG', '00852-54682464', 'Hong Kong Andeo Group Limited', '東莞市慕聲商貿有限公司', 'Hong Kong Andeo Group Limited', '012-878-0-001234-5', 'Bank of China (Hong Kong) Limited', 'Bank of China Tower, 1 Garden Road, Central, Hong Kong', 'BKCHHKHH', '2026-03-22 12:59:43', '2026-03-22 13:31:56', 0);
INSERT INTO `musheng_tax`.`t_document_party_config` (`id`, `site_code`, `buyer_name`, `buyer_address`, `buyer_phone`, `buyer_name_en`, `seller_name`, `seller_address`, `seller_phone`, `supplier_name`, `customer_name_tc`, `bank_account_name`, `bank_account_number`, `bank_name`, `bank_address`, `swift_code`, `create_time`, `update_time`, `deleted`) VALUES (7, 'MX', '东莞市慕声商贸有限公司', '广东省东莞市虎门镇连升路82号虎门万达广场2栋606房', '18575382420', 'Dongguan Musheng Trade Co., Ltd.', 'Hong Kong Andeo Group Limited', 'ROOM 1201, 12/F TAI SANG BANK BUILDING 130-132 DES VOEUX ROAD, CENTRAL HONGKONG', '00852-54682464', 'Hong Kong Andeo Group Limited', '東莞市慕聲商貿有限公司', 'Hong Kong Andeo Group Limited', '012-878-0-001234-5', 'Bank of China (Hong Kong) Limited', 'Bank of China Tower, 1 Garden Road, Central, Hong Kong', 'BKCHHKHH', '2026-03-22 12:59:43', '2026-03-22 13:31:56', 0);